platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/cli

inputs:
- name: bosh-shared-ci
- name: release_repo # The repo to create the final release for
- name: version # If version is provided, the version/version file will be used as the final version number.
  optional: true

outputs:
# The modified release_repo input with the new final release commit
- name: release_repo
# release_metadata contains the following files
# - version  - contains just the version number of the release that was created
# - tag-name - contains "v" followed by the version number. Useful in following tasks such as git pushes
#              that want to create a tag or the name attribute of a github release
# - empty-file - can be used for various purposes, ie. to clear release notes
# - $RELEASE_TARBALL_BASE_NAME-$version.tgz - the Bosh Final Release tarball created from 'bosh create-release --final --tarball=...'
#                                             Optional - if not defined, the tarball will just be named as the version
- name: release_metadata

run:
  path: bosh-shared-ci/tasks/release/create-final-release.sh

params:
  GIT_USER_NAME: # Name associated with the final release git commit
  GIT_USER_EMAIL: # Email associated with the final release git commit
  PRIVATE_YML: # The full private.yml file
  RELEASE_TARBALL_BASE_NAME: # (Optional) The base or "product" name for the tarball. Writes out a final release tarball in release_metadata/$RELEASE_TARBALL_BASE_NAME-$release-version.tgz
