---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/security-scanner

inputs:
- name: bosh-shared-ci
- name: patched_cves # The output provided by the `check-for-patched-cves` task.

run:
  path: bosh-shared-ci/tasks/release/ensure-cve-checker-succeeded.sh

params:
