---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/security-scanner

inputs:
- name: bosh-shared-ci
- name: task-output-folder # The output provided by the task being checked. The output folder is expected to have a `success` file in the root.

run:
  path: bosh-shared-ci/tasks/release/ensure-task-succeeded.sh

params:
