---
jobs:
  - name: build-docker-image
    plan:
      - in_parallel:
        - get: daily
          trigger: true
        - get: bosh-shared-ci
        - get: jammy-registry-image
        - get: trivy-github-release
          trigger: true
          params:
            globs:
              - trivy_*_Linux-64bit.tar.gz
      - task: prepare-docker-env
        image: jammy-registry-image
        config:
          platform: linux
          run:
            path: /bin/sh
            args:
              - -c
              - |
                apt update -y
                apt -y install ca-certificates
                tar xvf trivy-github-release/trivy*.tar.gz -C bosh-shared-ci/dockerfiles/security-scanner trivy
                bosh-shared-ci/dockerfiles/security-scanner/trivy filesystem --cache-dir bosh-shared-ci/dockerfiles/security-scanner/trivy-cache --download-db-only
                bosh-shared-ci/dockerfiles/security-scanner/trivy filesystem --cache-dir bosh-shared-ci/dockerfiles/security-scanner/trivy-cache --download-java-db-only
          inputs:
            - name: bosh-shared-ci
            - name: trivy-github-release
          outputs:
            - name: bosh-shared-ci
          params:
            GITHUB_TOKEN: ((github_public_repo_token))
      - put: bosh-security-scanner-image
        params:
          build: "bosh-shared-ci/dockerfiles/security-scanner"
resources:
  - name: bosh-shared-ci
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-shared-ci.git
      private_key: ((github_deploy_key_bosh-shared-ci.private_key))
  - name: trivy-github-release
    type: github-release
    source:
      access_token: ((github_public_repo_token))
      owner: aquasecurity
      repository: trivy
  - name: bosh-security-scanner-image
    type: docker-image
    source:
      repository: bosh/security-scanner
      username: ((dockerhub_username))
      password: ((dockerhub_password))
  - name: jammy-registry-image
    type: registry-image
    source:
      repository: ubuntu
      tag: jammy
      username: ((dockerhub_username))
      password: ((dockerhub_password))
  - name: daily
    type: time
    source:
      interval: 24h
